const airports = {
    ICN: {
        iata: "ICN",
        icao: "RKSI",
        name: "인천",
        fullName: "Incheon Intl.",
        city: "Seoul",
        lat: 37.4602,
        lng: 126.4407,
    },
    SFO: {
        iata: "SFO",
        icao: "KSFO",
        name: "샌프란시스코",
        fullName: "San Francisco Intl.",
        city: "San Francisco",
        lat: 37.6213,
        lng: -122.379,
    },
    LAX: {
        iata: "LAX",
        icao: "KLAX",
        name: "로스앤젤레스",
        fullName: "Los Angeles Intl.",
        city: "Los Angeles",
        lat: 33.9416,
        lng: -118.4085,
    },
    JFK: {
        iata: "JFK",
        icao: "KJFK",
        name: "뉴욕",
        fullName: "John F Kennedy Intl.",
        city: "New York",
        lat: 40.6413,
        lng: -73.7781,
    },
    NRT: {
        iata: "NRT",
        icao: "RJAA",
        name: "도쿄 나리타",
        fullName: "Narita Intl.",
        city: "Tokyo",
        lat: 35.772,
        lng: 140.3929,
    },
    HND: {
        iata: "HND",
        icao: "RJTT",
        name: "도쿄 하네다",
        fullName: "Haneda",
        city: "Tokyo",
        lat: 35.5494,
        lng: 139.7798,
    },
    LHR: {
        iata: "LHR",
        icao: "EGLL",
        name: "런던 히스로",
        fullName: "Heathrow",
        city: "London",
        lat: 51.47,
        lng: -0.4543,
    },
    CDG: {
        iata: "CDG",
        icao: "LFPG",
        name: "파리 샤를드골",
        fullName: "Charles de Gaulle",
        city: "Paris",
        lat: 49.0097,
        lng: 2.5479,
    },
    SIN: {
        iata: "SIN",
        icao: "WSSS",
        name: "싱가포르",
        fullName: "Changi",
        city: "Singapore",
        lat: 1.3644,
        lng: 103.9915,
    },
    AMS: {
        iata: "AMS",
        icao: "EHAM",
        name: "암스테르담",
        fullName: "Amsterdam Schiphol",
        city: "Amsterdam",
        lat: 52.3105,
        lng: 4.7683,
    },
    HEL: {
        iata: "HEL",
        icao: "EFHK",
        name: "헬싱키",
        fullName: "Helsinki",
        city: "Helsinki",
        lat: 60.3172,
        lng: 24.9633,
    },
    EWR: {
        iata: "EWR",
        icao: "KEWR",
        name: "뉴어크",
        fullName: "Newark Liberty Intl.",
        city: "Newark",
        lat: 40.6895,
        lng: -74.1745,
    },
    BLR: {
        iata: "BLR",
        icao: "VOBL",
        name: "벵갈루루",
        fullName: "Kempegowda Intl.",
        city: "Bengaluru",
        lat: 13.1986,
        lng: 77.7066,
    },
};

export default airports;
